### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by haveaprob** [kmccmk9/Yu-Gi-Oh-TTS-Deck-Builder#25]
When I go into tabletop simulator and click on the object it won't appear for me to place

**Comment by kmccmk9** [comment]
I've identified the issue. The first issue was that YGO Pro started adding trailing whitespaces. The second issue was that Imgur imposes a strict 10 MB file upload limit, so I reduced image quality a little to compensate for our increased files size. I will have an update pushed to the Microsoft App Store very shortly.
